# fly.toml app configuration file generated for frosty-snow-9061 on 2023-05-18T16:00:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frosty-snow-9061"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
