# fly.toml app configuration file generated for smart-brain-api on 2023-08-21T17:48:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smart-brain-api"
primary_region = "ams"

[build]

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
